name: liquor_journal
description: A Flutter app for tracking and rating spirits and cocktails
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.4.0
  riverpod_annotation: ^2.1.1
  
  # Routing
  go_router: ^10.1.2
  
  # Backend Integration
  pocketbase: ^0.23.0
  http: ^1.1.0
  flutter_dotenv: ^5.2.1
  
  # Local Database
  floor: ^1.4.2
  sqflite: ^2.3.0
  
  # UI Components
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.7
  cached_network_image: ^3.2.3
  
  # Barcode Scanning
  mobile_scanner: ^3.4.1
  
  # Speech Recognition
  speech_to_text: ^7.2.0
  
  # Image Handling
  image_picker: ^1.0.4
  image: ^4.1.1
  
  # Utilities
  intl: ^0.18.1
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  connectivity_plus: ^4.0.2
  permission_handler: ^11.0.1
  uuid: ^4.0.0
  crypto: ^3.0.3
  
  # Charts
  fl_chart: ^0.63.0
  
  # JSON Serialization
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  sqflite_common_ffi_web: ^0.4.5+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  build_runner: ^2.4.6
  floor_generator: ^1.4.2
  riverpod_generator: ^2.2.3
  json_serializable: ^6.7.1
  freezed: ^2.4.5
  
  # Linting
  flutter_lints: ^5.0.0
  
  # Testing
  integration_test:
    sdk: flutter
  mockito: ^5.4.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  
  # To add assets to your application, add an assets section, like this:
  assets:
    - .env

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
